import type { NextPage } from "next";
import Head from "next/head";
import SocialRow from "../components/socialRow";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="px-8 flex flex-col justify-center space-y-8">
        <h1>Hi!</h1>
        <p className="text-2xl">
          Welcome to the personal blog of <a href="/about">Viktor Nyblom</a>.
          <br />
          Stockholm based entrepreneur, investor and startup advisor.
        </p>
        <p className="text-2xl">
          I do many different things during the course of a year. But if you
          want to know what I'm doing right now, checkout my{" "}
          <a href="/now/">Now Page</a>.
        </p>
        <SocialRow />
      </div>
    </div>
  );
};

export default Home;
